name: eslint

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    branches:
      - '*'

jobs:
  eslint:
    name: Run eslint/prettier scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: Run linters
        run: |
          npx eslint
          npx prettier --list-different  .
